<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create success.' => '创建成功',
    'Delete success.' => '删除成功',
    'ID' => '',
    'Update success.' => '更新成功',
    'Create' => '创建',
    'Create Tag' => '创建Tag',
    'Delete Tag' => '删除Tag',
    'Description' => '描述',
    'Frequency' => '热度',
    'Hot Topic' => '热门标签',
    'Keyword' => '关键词',
    'Letter' => '首字母',
    'Manage Tag' => 'Tag管理',
    'More' => '更多',
    'Operation' => '操作',
    'Reset' => '重置',
    'Search' => '搜索',
    'Slug' => '标识',
    'Tag' => '标签',
    'This name has already been taken' => '该名称已被使用',
    'Title' => '标题',
    'Update' => '更新',
    'Update Tag' => '更新Tag',
];
